//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrkToolkit.Domain.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrkToolkit.Domain.CoreUnitTests.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error1 Hello.
        /// </summary>
        public static string Error1_Hello {
            get {
                return ResourceManager.GetString("Error1_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorldCode &quot;{0}&quot;.
        /// </summary>
        public static string Error1_World {
            get {
                return ResourceManager.GetString("Error1_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here is a format =&gt; {0} &lt;=.
        /// </summary>
        public static string Lalala_Infinity {
            get {
                return ResourceManager.GetString("Lalala_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string Lalala_Many {
            get {
                return ResourceManager.GetString("Lalala_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        public static string Lalala_One {
            get {
                return ResourceManager.GetString("Lalala_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here is a format =&gt; {0} &lt;=.
        /// </summary>
        public static string NestedClass_Lululu_Infinity {
            get {
                return ResourceManager.GetString("NestedClass_Lululu_Infinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string NestedClass_Lululu_Many {
            get {
                return ResourceManager.GetString("NestedClass_Lululu_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        public static string NestedClass_Lululu_One {
            get {
                return ResourceManager.GetString("NestedClass_Lululu_One", resourceCulture);
            }
        }
    }
}
