
#if ASS_DOMAIN
namespace SrkToolkit.Domain.Internals
#else
namespace SrkToolkit
#endif
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Resources;
    using System.Globalization;

    /// <summary>
    /// Helps you work with enums.
    /// </summary>
#if ASS_DOMAIN
    internal static class EnumTools
#else
    public static class EnumTools
#endif
    {
        /// <summary>
        /// Gets the description of a enum value from a resource file.
        /// </summary>
        /// <remarks>
        /// The key for the description is [EnumTypeName]_[EnumValueAsString].
        /// </remarks>
        /// <typeparam name="TEnum">The type of the enum.</typeparam>
        /// <param name="value">The value.</param>
        /// <param name="resourceManager">The resource manager generated by the resource file.</param>
        /// <returns>A localized description of the value or the value itself as string.</returns>
        public static string GetDescription<TEnum>(TEnum value, ResourceManager resourceManager)
            where TEnum : struct
        {
            return GetDescription(value, resourceManager, null);
        }

        public static string GetDescription<TEnum>(TEnum value, ResourceManager resourceManager, CultureInfo culture)
            where TEnum : struct
        {
            if (resourceManager == null)
                throw new ArgumentNullException("resourceManager");

            string key = value.GetType().Name + "_" + value.ToString();
            string result = resourceManager.GetString(key, culture);
            return result ?? value.ToString();
        }
    }
}
